src/components/Footer.tsx
src/components/Header.tsx
src/pages/Home.tsx

Header.tsx에 헤더부분 Navbar생성
<br>
- Header.tsx에 헤더부분 Navbar생성
- Home.tsx, Footer.tsx 텍스트 제거
<br>
- git pull 하신다음 npm i 하셔야 fontawesome 불러와집니다.
<br>
close #7

Feat: Header Navbar생성

---

firebaseConfig.ts
index.html
src/App.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/Login/Login.tsx
src/components/SignUp/SignUp.tsx
src/pages/Home.tsx

- 회원가입 및 로그인 파이어베이스 연동완료
- 라우터 수정
<br>
- 라우터 수정하였습니다.
- 회원가입 및 로그인 파이어베이스 연동만 하였습니다.
<br>
- 회원가입 및 로그인 파이어베이스 연동만 하였습니다. 퍼블리싱만 해주시면 될것같습니다.
<br>
close #9

회원가입 및 로그인 파이어베이스 연동완료

---

src/components/Header.tsx

- Header.tsx에 Navbar를 수정하였습니다.
<br>
- Header.tsx에 Navbar부분을 position을 사용하지 않기로 하였습니다.
<br>
- 
<br>
close #11

Fix: navbar수정

---

src/components/Login/Login.tsx

- 로그인 회원가입 구현 기능 과 css 합체
<br>
- 로그인 창에 회원가입 추가
<br>
- 로그인 및 회원가입을 한 페이지에 합쳤으니 signup.tsx는 삭제해도 괜찮을껏 같습니다.
<br>
close #13

Feat: 로그인 회원가입 css추가

---

src/components/Footer.tsx
src/components/Header.tsx

- Header.tsx 수정
- Footer.tsx 수정
<br>
- Header.tsx와 Footer.tsx @media screen and (max-width: 600px) {} 으로 잡아두었습니다.
- 모바일 반응형에 대응하도록 설계하였습니다.
<br>
- Header.tsx와 Footer.tsx @media screen and (max-width: 600px) {} 으로 잡아두었습니다. 
모바일은 600px, pc는 1024px 기준으로 작업해주시면 좋을것 같습니다.
<br>
close #25

리팩토링 Header, Footer

---

src/components/Home/BookSection.tsx
src/pages/Home.tsx

- 폴더삭제, 스타일컴포넌트 위치변동 라우팅명 변경
<br>
<br>
<br>
close #28

style:파일,스타일컴포넌트위치변경

---

src/App.tsx
src/components/Home/Carousel.tsx
src/components/Login/Login.tsx
src/components/Profile/MyPage.tsx

- 마이페이지 css 제작및 캐러셀 수정.
<br>
- 마이페이지 전체적인 구조를 만들었습니다.
<br>
- 없습니다~.
<br>
close #24

Feat: "마이페이지 구현"

---

src/App.tsx
src/components/Home/Carousel.tsx
src/components/Login/Login.tsx
src/components/Profile/MyPage.tsx

- 마이페이지 및 캐러셀에 코드리뷰중 나온 버그 수정.
<br>
- 마이페이지. 캐러셀 버그 수정.
<br>
- 없습니다..
<br>
close #33

fix: "마이페이지, 캐러셀 버그수정"

---

src/components/Header.tsx
src/components/Home/Carousel.tsx

- Header z-index 수정, Carousel상단마진줄이기
<br>
- Header.tsx z-index를 9999로 변경하였습니다.
- Carouse 상단마진을 50px로 변경하였습니다.
<br>
- git pull origin main해서 작업해주세요
<br>
close #35

Style: Header z-index 수정, Carousel상단마진줄이기

---

src/App.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/Modal/Review.tsx
src/pages/Board.tsx
src/pages/List.tsx
src/pages/Login.tsx
src/pages/MyPage.tsx
src/pages/Search.tsx

- 생각없이 components로 분리했던거 pages로 옮기는 작업을 했습니다
<br>
- Filechanged가셔서 바뀐코드 참고하시면 될것같습니다
<br>
- **꼭 변경점 확인하시고 자기브랜치에 해당사항 땡겨와서 작업하시길 바랍니다. 꼭!**
<br>
close #37

Refact: components와 pages구분

---

package-lock.json
package.json
src/components/Header.tsx
src/components/Modal/Review.tsx
src/pages/List.tsx

- 리뷰모달부분을 개발하였습니다. Review.tsx
<br>
- 큰 변경사항은 List.tsx페이지가 생긴것과 모달버튼을 누르면 Review가 나오도록 하였습니다.
<br>
- 모달은 react-modal 라이브러리 사용하기로 했습니다. 이점 참고해주세요! npm i 하시면 깔립니다.
<br>
close #39

Feat: 리뷰모달부분 개발

---

src/components/Home/BookImage/BookSection.tsx
src/components/Home/BookImage/BookSection1.tsx
src/components/Home/BookImage/BookSection2.tsx
src/components/Home/BookImage/BookSection3.tsx
src/components/Home/BookImage/BookSection4.tsx
src/components/Home/BookImage/BookSection5.tsx
src/components/Modal/Review.tsx
src/pages/List.tsx

- Review.tsx모달 반응형작업을 하였습니다
<br>
- Review.tsx모달 반응형작업을 하였습니다
<br>
- X
<br>
close #41

style: 리뷰페이지 반응형작업

---

src/pages/List.tsx

<br>리스트페이지 코드 수정
<br>
<br>
close #53

feat:리스트페이지 코드 수정

---

src/components/Home/Carousel.tsx

- dot 수정
<br>
- node 안에 있는 css 수정.
<br>
- 없습니다.
<br>
close #51

design: dot수정

---

src/pages/List.tsx

<br>list페이지 개발
<br>
<br>
close #56

feat:list페이지 개발

---

src/components/Board/BoardDetail.tsx
src/components/Board/BoardWrite.tsx
src/contexts/AuthContext.tsx
src/main.tsx
src/pages/Board.tsx

- 게시판 기능 추가(css는 추후 추가예정).
<br>
- 게시판 상세기능에 대한 메인 기능 추가 주로 작성한 게시물이랑 댓글.
<br>
- 없습니다.
<br>
close #57

Feat: 게시판상세 기능추가

---

src/components/Modal/BookAdd.tsx
src/pages/List.tsx

- BookAdd.tsx모달 List.tsx와 연결
<br>
- BookAdd.tsx모달 List.tsx와 연결하였습니다. (FileChanged로 봐주세요)
<br>
- 로직변경된거 확인 부탁드립니다
<br>
close #66

Fix: List.tsx 로직 수정 및 변경

---

src/components/Modal/Review.tsx
src/pages/List.tsx

- List.tsx에 요소(사진과 정보들)삭제버튼 구현
<br>
- List.tsx에 요소(사진과 정보들)삭제버튼 구현
<br>
- X
<br>
close #68

Feat: 요소삭제버튼 구현

---

src/components/Board/BoardDetail.tsx
src/components/Modal/Intro.tsx
src/pages/MyPage.tsx

- 마이페이지 uid통해서 프로필 사진 작동, 닉네임 작동 boarddetail css및 댓글기능 임시추가.
<br>
- 작업내용과 동일.
<br>
- npm i 한번 해주세요.
<br>
close #65

feat : 게시판 상세페이지 및 댓글추가

---

package-lock.json
package.json
src/components/Loader/Loader.tsx
src/components/Modal/Intro.tsx
src/pages/Board.tsx
src/pages/Home.tsx
src/pages/List.tsx
src/pages/Login.tsx
src/pages/MyPage.tsx

Loader.tsx 로딩애니메이션 구현
Intro.tsx 변수이름등 카멜케이스 적용
Pages있는 대부분의 파일들 로딩애니메이션 적용
<br>
Loader.tsx 로딩애니메이션 구현
Intro.tsx 변수이름등 카멜케이스 적용
Pages있는 대부분의 파일들 로딩애니메이션 적용
<br>
- 대부분 파일에 로딩애니메이션을 추가하고 컨벤션을 맞추느라 변경된점이 많습니다 꼭 git pull받으셔서 충돌해결하시고 작업하시길 바랍니다.
<br>
close #70

로딩애니메이션 구현 및 일부파일 수정

---

package-lock.json
package.json
src/App.tsx
src/components/Modal/BookAdd.tsx

- Toast alert구현
<br>
- Toast alert구현
<br>
- 꼭 git pull 하시고 npm i 해주세요
<br>
close #74

Feat: Toast alert구현

---

src/pages/List.tsx
src/pages/MyPage.tsx

- List페이지 스타일을 변경하였습니다.
<br>
- List페이지 한줄에 책과 책정보 4개씩 그이상은 아래로 배치하게 해두었습니다.
<br>
- 없습니다
<br>
close #77

List페이지 스타일변경

---

src/components/Board/BoardDetail.tsx
src/components/Board/BoardWrite.tsx
src/pages/Board.tsx

- 게시판 view, likes 추가.
<br>
- 게시판 클릭시 view +1 자동생성, 게시판 세부페이지에서 좋아요버튼 클릭시 likes자동+1, 변수명 변경.
<br>
- 없음.
<br>
close #78

Feat: 게시판 likes views 추가

---

src/pages/List.tsx

<br>리스트페이지 검색기능 구현
<br>검색기능 기능
<br>없습니다
close #59

feat:리스트페이지 검색기능 구현

---

src/pages/List.tsx

<br>검색창 스타일링
<br>스타일링 변경
<br> .
close #84

style:검색창 스타일링

---

src/components/Board/BoardDetail.tsx
src/pages/Board.tsx
src/pages/Login.tsx

- 로그인 회원가입 추가 기능, 게시판 css추가.
<br>
- 회원가입시 로그인으로 자동이동, 로그인시 메인으로 이동, 게시판 css 및 상세페이지에서 뒤로가기 버튼추가.
<br>
- 없음.
<br>
close #89

feat :로그인 이동 및 게시판 css 및 버튼추가

---

src/components/Board/BoardDetail.tsx
src/pages/Board.tsx

- 게시판 수정 창 및 게시판 마진 탑 줄어듬.
<br>
- 게시판 수정 가능
<br>
- 없습니다.
<br>
close #94

feat:updateboard

---

src/components/Board/BoardDetail.tsx
src/components/Board/BoardWrite.tsx
src/pages/Board.tsx

- 게시판 작성시간 구현 및 게시판 작성시간 기준 내림차선.
<br>
- Board 메인에 작성시간 표시 및 내림차선, Boarddetail에 작성시간 표시.
<br>
- 없습니다.
<br>
close #96

feat: 게시판 내림차순

---

src/pages/List.tsx

<br>list페이지 반응형
<br>
<br>
close #92

design:list페이지 반응형

---

src/pages/List.tsx

<br> 반응형작업
<br> list페이지 미디어쿼리 작용
<br>
close #100

style:반응형작업

---

src/pages/List.tsx

style:주석제거

---

src/components/Board/BoardDetail.tsx
src/components/Loader/Loader.tsx
src/pages/Board.tsx
src/pages/List.tsx
src/pages/Login.tsx
src/pages/MyPage.tsx

<br>전페이지 주석제거
BoardDetail부분 주석제거가 많았습니다. 확인부탁드러요
BoardDetail 영어주석부분도 삭제했습니다.
<br>
close #108

style:전페이지 주석제거

---

src/pages/Login.tsx

<br>로그인불가때 문구출력 수정
<br>로그인불가때 문구출력 수정
<br>
close #110

style:로그인불가때 문구출력 수정

---

README.md

- README.md 중간수정
<br>
- README.md 중간수정
<br>
- X
<br>
- X

README.md 중간수정

---

README.md

-  README 이미지경로 수정
<br>
-  README 이미지경로 수정
<br>
- X
<br>
- X

Fix: README 이미지경로 수정

---

src/pages/Login.tsx

<br>login부분 변동
<br> Forgot Password부분 삭제
<br> x
close #115

style:login부분 변동

---

README.md
src/components/Board/BoardDetail.tsx
src/components/Home/DesignBookStyle.tsx
src/components/Modal/BookAdd.tsx
src/components/Modal/Intro.tsx
src/components/Modal/Review.tsx
src/contexts/AuthContext.tsx
src/hooks/useAuthState.ts
src/pages/Board.tsx
src/pages/List.tsx
src/pages/MyPage.tsx
src/types/Board.ts
src/types/BoardDetail.ts
src/types/BookAdd.ts
src/types/Intro.ts
src/types/List.ts
src/types/MyPage.ts
src/types/Review.ts

- 타입과 커스텀훅스폴더를 따로 만들고 할당해주었습니다.
<br>
- FileChanged 확인해주세요
- 큰 변경점으로는 hooks폴더와 types폴더가 생겼고 코드를 분리해주었습니다
<br>
- 크게 변경하였으니 꼭봐주세요
<br>
close #118

타입과 커스텀훅스 따로 지정

---

README.md
src/pages/List.tsx
src/pages/MyPage.tsx
src/styles/ListModalStyle.ts
src/styles/MyPageModalStyles.ts

- styles폴더를 만들어 모달스타일링을 분리해두었습니다.
<br>
- styles폴더를 만들어 모달스타일링을 분리해두었습니다.
<br>
-  폴더구조 유의하세요
<br>
- X

Refact: style분리

---

src/components/Modal/Review.tsx

<br>책리뷰 페이지 모달 반응형수정
<br>.
<br>.
close #122

style:반응형 수정

---

src/components/Modal/Intro.tsx
src/styles/MyPageModalStyles.ts

- 인트로 모달 반응형 수정.
<br>
- 인트로 모달 반응형 수정
<br>
- 없음.
<br>
close #128

design: 인트로 반응형

---

src/App.tsx
src/components/Header.tsx
src/pages/Logout.tsx

- 로그아웃
<br>
- 로그 아웃 기능 추가.
<br>
- 없읍.
<br>
close #130

feat: logout
